Before we can create any actions using command objects, we need a controller. Create a
`PlayerController` class to work with the existing domain object `Player`.

[source,groovy]
----
$ ./grailsw create-controller demo.Player
----

NOTE: The first time you run a `grails` command, application dependencies will be
downloaded form the Internet. Subsequent calls will be much faster.

The output of the command will look like:

----
| Created grails-app/controllers/demo/PlayerController.groovy
| Created src/test/groovy/demo/PlayerControllerSpec.groovy
----

You will now have a new, mostly empty controller named `PlayerController.groovy`
in the `grails-app/controllers/demo` directory. Update the `index` action and add
the `show` action to look like this:

[source,groovy]
----
include::{sourceDir}/grails-app/controllers/demo/PlayerController.groovy[tags=indexShow]
----

The domain class, views, and some sample data are provided for you. At this point,
you should be able to run the application and navigate to http://localhost:8080/player/
to see a list of players, and click on a player's name to view that individual player.
However, none of the other actions (e.g. create, save, edit, update, delete) will work yet,
not until you write those actions.

[NOTE]
====
At any point, you can start the application by typing `./gradlew bootRun` on the
command line; it is running and ready when you see:

    Grails application running at http://localhost:8080 in environment: development

Stop the application by pressing *Ctrl-C*.
====
